# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62lockchain.proto\x12\nadarsh.dsc\"+\n\x0e\x62\x61lanceRequest\x12\x19\n\x11wallet_public_key\x18\x01 \x01(\t\"\x1d\n\x0c\x62\x61lanceReply\x12\r\n\x05value\x18\x01 \x01(\x01\"\xaa\x01\n\x0c\x62lockRequest\x12\x12\n\nblock_size\x18\x01 \x01(\x05\x12(\n\x06header\x18\x02 \x01(\x0b\x32\x18.adarsh.dsc.block_header\x12\x1b\n\x13transaction_counter\x18\x03 \x01(\x05\x12\x10\n\x08reserved\x18\x04 \x01(\t\x12-\n\x0ctransactions\x18\x05 \x03(\x0b\x32\x17.adarsh.dsc.transaction\"\x83\x01\n\x0c\x62lock_header\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x1b\n\x13previous_block_hash\x18\x02 \x01(\t\x12\x0f\n\x07\x62lockID\x18\x03 \x01(\x05\x12\x11\n\ttimestamp\x18\x04 \x01(\x05\x12\x12\n\ndifficulty\x18\x05 \x01(\x05\x12\r\n\x05nonce\x18\x06 \x01(\t\"\x9a\x01\n\x0btransaction\x12\x1d\n\x15sender_public_address\x18\x01 \x01(\t\x12\x1f\n\x17recepeint_pubic_address\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x01\x12\x11\n\ttimestamp\x18\x04 \x01(\x05\x12\x16\n\x0etransaction_id\x18\x05 \x01(\t\x12\x11\n\tsignature\x18\x06 \x01(\t\"9\n\x12new_block_response\x12\x12\n\nblock_hash\x18\x01 \x01(\t\x12\x0f\n\x07\x62lockID\x18\x02 \x01(\x05\"$\n\x11new_block_request\x12\x0f\n\x07request\x18\x01 \x01(\x05\"\n\n\x08response2\xe5\x01\n\nblockchain\x12?\n\x07\x62\x61lance\x12\x1a.adarsh.dsc.balanceRequest\x1a\x18.adarsh.dsc.balanceReply\x12@\n\x0e\x62lock_creation\x12\x18.adarsh.dsc.blockRequest\x1a\x14.adarsh.dsc.response\x12T\n\x13metronome_blockHash\x12\x1d.adarsh.dsc.new_block_request\x1a\x1e.adarsh.dsc.new_block_responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'blockchain_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BALANCEREQUEST']._serialized_start=32
  _globals['_BALANCEREQUEST']._serialized_end=75
  _globals['_BALANCEREPLY']._serialized_start=77
  _globals['_BALANCEREPLY']._serialized_end=106
  _globals['_BLOCKREQUEST']._serialized_start=109
  _globals['_BLOCKREQUEST']._serialized_end=279
  _globals['_BLOCK_HEADER']._serialized_start=282
  _globals['_BLOCK_HEADER']._serialized_end=413
  _globals['_TRANSACTION']._serialized_start=416
  _globals['_TRANSACTION']._serialized_end=570
  _globals['_NEW_BLOCK_RESPONSE']._serialized_start=572
  _globals['_NEW_BLOCK_RESPONSE']._serialized_end=629
  _globals['_NEW_BLOCK_REQUEST']._serialized_start=631
  _globals['_NEW_BLOCK_REQUEST']._serialized_end=667
  _globals['_RESPONSE']._serialized_start=669
  _globals['_RESPONSE']._serialized_end=679
  _globals['_BLOCKCHAIN']._serialized_start=682
  _globals['_BLOCKCHAIN']._serialized_end=911
# @@protoc_insertion_point(module_scope)
