# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import metronome_pb2 as metronome__pb2


class metronomeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_details = channel.unary_unary(
                '/adarsh.dsc.metronome/get_details',
                request_serializer=metronome__pb2.validatorRequest.SerializeToString,
                response_deserializer=metronome__pb2.validatorResponse.FromString,
                )


class metronomeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_details(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_metronomeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_details': grpc.unary_unary_rpc_method_handler(
                    servicer.get_details,
                    request_deserializer=metronome__pb2.validatorRequest.FromString,
                    response_serializer=metronome__pb2.validatorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'adarsh.dsc.metronome', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class metronome(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_details(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/adarsh.dsc.metronome/get_details',
            metronome__pb2.validatorRequest.SerializeToString,
            metronome__pb2.validatorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
